# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
project_name: hierarchy
env:
  - CGO_ENABLED=0
before:
  hooks:
    - go mod tidy
builds:
  - ldflags:
      - "-X {{.Env.VERSION_PKG}}.Branch={{.Env.BRANCH}}"
      - "-X {{.Env.VERSION_PKG}}.BuildDate={{.Env.DATE}}"
      - "-X {{.Env.VERSION_PKG}}.GitSHA1={{.Env.COMMIT}}"
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  skip: false
